Arrays
DmitrijsRuskovs/Training01 pull request #14
Opened 2021-07-19 14:03 UTC by DmitrijsRuskovs

2021-07-19 20:01 UTC, ausmoons requested changes

2021-07-19 20:01 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/Excercise6/Program.cs
> +            for (int i = 0; i < arraySize; i++) myArray[i] = rnd.Next(arraySize);
Ieliec {}, kur vajag

2021-07-19 20:01 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/TicTacToe/Program.cs
> +                turnOfX = !turnOfX;
Pat ja šis strādā, tas nav diez ko saprotams

2021-07-19 20:01 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/TicTacToe/Program.cs
> +            if (SomebodyWon()) {
{ jaunā rindā

2021-07-19 20:01 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/TicTacToe/Program.cs
> +                    if (board[r, c] == ' ') result = false;
Par ja tu atrodi tukšu sākumā, tu turpini visam iet cauri?

2021-07-20 06:31 UTC, DmitrijsRuskovs commented on csharp-basics/exercises/Arrays/Arrays/TicTacToe/Program.cs
> +                turnOfX = !turnOfX;
Vai runa iet par šo:

turnOfX = !turnOfX;

bool turnOfX ==true, kad staigā X. Tiklīdz pastaigājis, turnOfX=!turnOfX, jeb staigā O, tad atkal tālāk turnOfX=!turnOfX, jeb atkal X.

2021-07-20 06:33 UTC, DmitrijsRuskovs commented on csharp-basics/exercises/Arrays/Arrays/TicTacToe/Program.cs
> +                turnOfX = !turnOfX;
Tas ir vieglākais vispārpieņemtais algoritms, kā pārslēgties no divām plūsmām pēc kārtas.

2021-07-20 06:34 UTC, DmitrijsRuskovs commented on csharp-basics/exercises/Arrays/Arrays/TicTacToe/Program.cs
> +                turnOfX = !turnOfX;
...ar vienu bita-mainīgo

2021-07-20 06:39 UTC, DmitrijsRuskovs commented on csharp-basics/exercises/Arrays/Arrays/TicTacToe/Program.cs
> +                    if (board[r, c] == ' ') result = false;
Te ir tikai  9 pārbaudes!!!! Bet liekais break neko nemainīs, tikai padarīs lielāku nelasāmāku kodu

2021-07-20 08:19 UTC, closed without merging