Public api fetch
DmitrijsRuskovs/Training01 pull request #26
Opened 2021-08-17 10:22 UTC by DmitrijsRuskovs

2021-08-17 19:44 UTC, ausmoons requested changes

2021-08-17 19:44 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/CalculateArea/Geometry.cs
>          public static double areaOfCircle(decimal radius)
Metode ar lielo burtu

2021-08-17 19:44 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/CheckOddEven.Test/UnitTest1.cs
> +            bool result = CheckOddEven.Program.IsIntegerOdd(4);
Vispirms arrange, tad act

2021-08-17 19:44 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/TestProject1/UnitTest1.cs
> +            //Act
Šeit var bez komentāra. Ka ir liels setup tad mēdz atsevišķi pielikt komentārus

2021-08-17 19:44 UTC, ausmoons commented on csharp-basics/exercises/Scooters/Scooters.Test/RentalCompanyTest.cs
> +            //Act
Vienā testā viens act ko tad arī pārbauda. Ja šo visu vajag vienam testam, tad to dara pie arrange

2021-08-17 19:44 UTC, ausmoons commented on csharp-basics/exercises/Scooters/Scooters.Test/RentalCompanyTest.cs
> +            //Act
ACt bez assert noteikti nav vajadzīgs

2021-08-19 13:24 UTC, EdgarsSalmins commented on csharp-basics/exercises/Scooters/Scooters/Program.cs
> +    public class Program
Console app jādzēš ārā no scooteriem. :) projektam jābūt ar tipu class library.

2021-08-21 19:35 UTC, closed without merging